### ISSUE TITLE
Add environment variable for changing the web interface port

### ISSUE THREAD

**Issue by ispiropoulos** [linuxserver/docker-pyload-ng#11]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Being able to change the default http access port (8000 to something else)

## Current Behavior

Cannot change it via environment variable

**Comment by aptalca** [comment]
You can map it to a different port. No need to change the internal port.

**Comment by ispiropoulos** [comment]
> You can map it to a different port. No need to change the internal port.

I know I can map it on a different port. I want to use this container on shared docker network where another container is using this port, and for some reasons I do not want to change it.

**Comment by Roxedus** [comment]
Fwiw a shared docker network would not give you issues

**Comment by aptalca** [comment]
I'm assuming they mean pyload is using another container's network (likely for vpn).
If so, it's an edge case so I'm not in favor of adding it as a feature globally, however, you can edit the pyload config file in the config folder.

This is the line you're looking for: https://github.com/linuxserver/docker-pyload-ng/blob/main/root/defaults/pyload.cfg#L42
And this is where it gets copied to: https://github.com/linuxserver/docker-pyload-ng/blob/main/root/etc/cont-init.d/30-config#L10-L12

**Comment by ispiropoulos** [comment]
> I'm assuming they mean pyload is using another container's network (likely for vpn). If so, it's an edge case so I'm not in favor of adding it as a feature globally, however, you can edit the pyload config file in the config folder.
> 
> This is the line you're looking for: https://github.com/linuxserver/docker-pyload-ng/blob/main/root/defaults/pyload.cfg#L42 And this is where it gets copied to: https://github.com/linuxserver/docker-pyload-ng/blob/main/root/etc/cont-init.d/30-config#L10-L12

Thank you @aptalca
