### ISSUE TITLE
Current SevenZip is 16.04, please update to a more recent one

### ISSUE THREAD

**Issue by BobSilent** [linuxserver/docker-pyload-ng#15]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
7z.org has now native linux distributions for 21.07
-   7zz         - standalone console version of 7-Zip (version compiled for dynamic system library linking)
-  7zzs        - standalone console version of 7-Zip (version compiled with static system library linking)

Please update from 16.04 (2016) to a more recent one 21.07 (2021)

please also create a link from 7zzs to /bin/7z

## Alternatives Considered
manually updated

**Comment by aptalca** [comment]
We pull from the alpine repo. You can report to them and once they update, our image will update also.
