### ISSUE TITLE
extract plugin: password list does not work

### ISSUE THREAD

**Issue by r2ixuz** [linuxserver/docker-pyload-ng#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
Extracting password protected rar-files should always work no matter which password is required.

## Current Behavior
When pyload-ng tries to extract an archive it uses only the first password from a passwords.txt defined file in the ExtractArchive plugin.

## Steps to Reproduce
Define a password file with multiple passwords in it at the ExtractArchive plugin.
Upgrade from linuxserver/docker-pyload to linuxserver/docker-pyload-ng (latest tag).
Extract an archive which will need for example the 3rd password in the password file. It will only try the first one and fail to extract.

## Environment
**OS:** gentoo
**CPU architecture:** x86_64
**How docker service was installed:**
from the distro repo (20.10.17)

## Command used to create docker container (run/create/compose/screenshot)
docker-compose up -d

**Comment by aptalca** [comment]
It sounds like an issue with the app, not the container. It should be reported upstream to pyload-ng
