### ISSUE TITLE
[BUG] a LOT of files in /tmp

### ISSUE THREAD

**Issue by cl0rm** [linuxserver/docker-pyload-ng#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

many files get created in /tmp/tmpXXXXXXXX (with the X's being random characters)
and with many I mean over a million files in a few months.
I have logging disabled.
This does not use a lot of storage, but the folder in overlayFS took away all my ext4 inodes, rendering a node useless.
This happened multiple times already, after a few months of uptime. Removing all files solves the problem, but takes a LOT of time.

### Expected Behavior

After a few thousand files a cleanup should happen.
I am aware of tmpfs, however over a million files is just crazy.

### Steps To Reproduce

running in a compose (below only the relevant part) together with wireguard container for internet access.
Everything works, except the extreme log spam and a rather high idle CPU usage (5-10% of a 3 GHz Intel Westmere core).
After a few months my 32GB system disk (NVME disk) 

### Environment

```markdown
- OS: debian 11 VM on debian 11/proxmox host. VM has 4GB RAM / 32 GB system disk.
- How docker service was installed: CLI with docker-compose file.
```

### CPU architecture

x86-64

### Docker creation

```bash
pyload-ng:
    image: lscr.io/linuxserver/pyload-ng
    container_name: pyload-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /opt/pyload:/config
      - /mnt/SMB_DOWNLOAD_DIR:/downloads
    depends_on:
      - wireguard
    network_mode: "service:wireguard"
#    ports:
#      - 8080:8000
```

### Container logs

```bash
pyLoad already running with pid 223

-> LOTs of these entries. LOTs. they seem to fly in faster than SSH can print out.
```

**Comment by aptalca** [comment]
A few things
1. `/tmp` folder is inside the container and based on what you reported, you haven't recreated your container in months. If you did, `/tmp` would be wiped along with the container. You could be hitting an old bug with pyload-ng.
2. Based on that repeating log message, your pyload-ng could be stuck in a restart loop, but without the rest of the log, it's hard to say.
3. You do not need to (and really should not) mess with files inside the container like mass deleting them. Just recreate the container.
