### ISSUE TITLE
[BUG] RAR-files are not extracted anymore

### ISSUE THREAD

**Issue by keqas** [linuxserver/docker-pyload-ng#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Downloaded RAR-Files are not extracted anymore since updating to _0.5.0b3.dev71-ls75_.
Release _develop-0dfaab92-ls240_ is still working fine.
Probably it's related to rebase to Alpine 3.18?!

### Expected Behavior

Downloaded RAR-Files are extracted successfully.

### Steps To Reproduce

1. Add any download link with RAR-file as target (pyLoad-plugin ExtractArchive must be activated)
2. wait until download has finished -> RAR-file will not be extracted

### Environment

```markdown
- OS: Synology DSM 7.2-64561
- How docker service was installed: "Container Manager" via integrated package manager("Package Center")
```

### CPU architecture

x86-64

### Docker creation

```bash
{
   "CapAdd" : [],
   "CapDrop" : [],
   "cmd" : "",
   "cpu_priority" : 50,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enable_service_portal" : null,
   "enabled" : false,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "PS1",
         "value" : "$(whoami)@$(hostname):$(pwd)\\$ "
      },
      {
         "key" : "HOME",
         "value" : "/config"
      },
      {
         "key" : "TERM",
         "value" : "xterm"
      },
      {
         "key" : "S6_CMD_WAIT_FOR_SERVICES_MAXTIME",
         "value" : "0"
      },
      {
         "key" : "S6_VERBOSITY",
         "value" : "1"
      },
      {
         "key" : "S6_STAGE2_HOOK",
         "value" : "/docker-mods"
      },
      {
         "key" : "VIRTUAL_ENV",
         "value" : "/lsiopy"
      },
      {
         "key" : "LSIO_FIRST_PARTY",
         "value" : "true"
      },
      {
         "key" : "PGID",
         "value" : "100"
      },
      {
         "key" : "PUID",
         "value" : "1029"
      },
      {
         "key" : "TZ",
         "value" : "Europe/Berlin"
      }
   ],
   "exporting" : false,
   "id" : "d1afd7e83464f7d6d8de612bb9fdcc8331084f2225e897abeb14000ca87fc2c4",
   "image" : "linuxserver/pyload-ng:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "linuxserver-pyload-ng-1",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 8000,
         "host_port" : 8000,
         "type" : "tcp"
      },
      {
         "container_port" : 9666,
         "host_port" : 9666,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "service_portals" : [],
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "use_host_network" : false,
   "version" : 2,
   "volume_bindings" : [
      {
         "host_volume_file" : "***/pyLoad",
         "is_directory" : true,
         "mount_point" : "/downloads",
         "type" : "rw"
      },
      {
         "host_volume_file" : "***/pyload-ng",
         "is_directory" : true,
         "mount_point" : "/config",
         "type" : "rw"
      }
   ]
}
```

### Container logs

```bash
> [...]
> 25543	2023-05-28 20:37:52	INFO	pyload	Download finished: ***.rar
> 25544	2023-05-28 20:37:52	INFO	pyload	Package finished: https://***.bz
> 25545	2023-05-28 20:37:52	INFO	pyload	ADDON ExtractArchive: Check package: https://***.**
> 25546	2023-05-28 20:37:52	INFO	pyload	ADDON ExtractArchive: ***.rar | Extract to: /downloads/
> 25547	2023-05-28 20:37:52	ERROR	pyload	ADDON ExtractArchive: ***.rar | Archive error | ERROR: /downloads/***.rar
> 25548	?	?	?	Cannot open the file as archive
> 25549	2023-05-28 20:37:52	ERROR	pyload	ADDON ExtractArchive: ***.rar | Extract failed
> [...]
```

**Comment by aptalca** [comment]
This is a weird and larger issue.

We attempt to install `p7zip`, which handles unrar. In the Dockerfile, we tell apk to install `p7zip`, but it seems in alpine 3.18, they deprecated `p7zip`, which now links to `7zip`.

The problem is, the upstream app needs to call 7zip instead of p7zip and in this case that's not happening (many upstream apps are hardcoded to call `7za or 7zr`, which don't exist in `7zip` and that's why we didn't switch them over to the newer and better `7zip`).

We'll have to think about this because it will affect many other apps as we rebase them to alpine 3.18.

We'll keep you posted here. Until then, you can either switch to the previous build tag, or the develop tag (which is not rebased yet).

**Comment by aptalca** [comment]
I just created a new container based on the latest and enabled the `ExtractArchive` addon, and is seems to detect 7zip properly.

`pyload  ADDON ExtractArchive: Found HjSplit 0.02 | Found SevenZip 22.01 | Found UnZip 3.11.3 | Found UnTar 3.11.3`

Not sure why it's failing, though. Perhaps should be reported to the developer of that addon.

**Comment by advorsky73** [comment]
the same issue happens on develop tag now.

**Comment by advorsky73** [comment]
it does not happen on develop-0dfaab92-ls240.

**Comment by keqas** [comment]
I've reported this issue to [pyload](https://pypi.org/project/pyload-ng/) project team as well: https://github.com/pyload/pyload/issues/4304

**Comment by advorsky73** [comment]
jfyi... this has nothing to do with pyload. its a faulty 7z in the container.

**Comment by aptalca** [comment]
Please do let us know how you came to that conclusion. 
The container uses this package: https://pkgs.alpinelinux.org/packages?name=7zip&branch=v3.18&repo=&arch=&maintainer=
The build logs are visible there.

Alpine issues don't show any reports related to this package in the last 5 years.

**Comment by advorsky73** [comment]
as stated before: 
> the same issue happens on develop tag now.
> it does not happen on develop-0dfaab92-ls240.
both of them have the same pyload.
thats how i came to that conclusion.

**Comment by aptalca** [comment]
> so chances are slim its on pyload...

Please read my comments above.

The big change between the images is switching from `p7zip` to `7zip`. Their binary names are the same, however it seems the arguments the addon uses seem to work with the older `p7zip` binary, while failing with the newer `7zip` binary.

The appropriate starting point is the arguments. In any case, we provide `7zip` from the alpine repo in the image. Upstream seems to support `7zip` so it's more appropriate for them to figure this out. Not us.

**Comment by advorsky73** [comment]
Its not about the arguments. A simple 
`7z x archive.rar `
will result in a failure saying its not a valid archive.
the 7z binary from develop-0dfaab92-ls240 does not have that issue on the same archive as it seems.

**Comment by aptalca** [comment]
Thanks for checking. I have a feeling alpine may have removed rar extraction capability from 7zip altogether. I recall they removed `unrar` from their repo due to license related reasons.

We can add `unrar` into this image if the addon supports that.

I'll get a PR build going if you guys are willing to test that

**Comment by advorsky73** [comment]
sure thing ill test it for you👍

**Comment by aptalca** [comment]
When the PR build pushes, there will be a comment in https://github.com/linuxserver/docker-pyload-ng/pull/32 with the image names and tags

**Comment by keqas** [comment]
RAR Extraction is working fine again in latest release [0.5.0b3.dev71-ls77](https://github.com/linuxserver/docker-pyload-ng/releases/tag/0.5.0b3.dev71-ls77)!
@aptalca: Thanks for fixing!
@advorsky73: Thanks for supporting!
