### ISSUE TITLE
[FEAT] Use pypy instead  of python to run pyload-ng

### ISSUE THREAD

**Issue by alex9434** [linuxserver/docker-pyload-ng#48]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like to suggest to use pypy3 from https://github.com/conda-forge/miniforge instead of cpython3 to run pyload-ng

### Reason for change

pypy uses significantly less cpu resources and runs pyload-ng fast even on low powered devices like raspberry pi. I have run pyload-ng with pypy and did not experience any issues

### Proposed code change

change template to install Miniforge-pypy3-Linux and necessary modules

**Comment by aptalca** [comment]
According to upstream pypy support is experimental

**Comment by alex9434** [comment]
I agree, but it works without problems here.
